name: Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    name: Scan code for secrets using Gitleaks
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks (scan)
        uses: zricethezav/gitleaks-action@v8
        with:
          args: '--no-git'  # scan the workspace only and don't require git history
